### ISSUE TITLE
/start: line 153: [: : integer expression expected - ./start: line 343: br_arr: bad array subscript

### ISSUE THREAD

**Issue by antivirtel** [juleast/GeneratePIF#4] opened 2024-01-26 03:50 UTC
Hi,

I seem to have errors when I try to use the tool, I'm in Termux on the phone. I have it cloned to /data/data/com.termux - I've tried it under /sdcard before (no +x, but same error).

Bulk mode:
<details><summary>Click to expand</summary>
<p>

```logtalk
/sdcard/pif-generator $ bash  ./start -f official.txt
----- Bulk generation mode -----
Cloning into 'asus_i007_1'...
remote: Enumerating objects: 1083, done.
remote: Counting objects: 100% (1083/1083), done.
remote: Compressing objects: 100% (752/752), done.
Receiving objects:  78% (845/1083), [192.00](http://192.0.0.0/) KiB | [362.Receiving](http://362.receiving/) objects:  79% (856/1083), [192.00](http://192.0.0.0/) KiB | [362.Receiving](http://362.receiving/) objects:  80% (867/1083), [192.00](http://192.0.0.0/) KiB | [362.Receiving](http://362.receiving/) objects:  81% (878/1083), [192.00](http://192.0.0.0/) KiB | [362.Receiving](http://362.receiving/) objects:  82% (889/1083), [192.00](http://192.0.0.0/) KiB | [362.Receiving](http://362.receiving/) objects:  83% (899/1083), [192.00](http://192.0.0.0/) KiB | [362.Receiving](http://362.receiving/) objects:  84% (910/1083), [192.00](http://192.0.0.0/) KiB | [362.Receiving](http://362.receiving/) objects:  85% (921/1083), [192.00](http://192.0.0.0/) KiB | [362.Receiving](http://362.receiving/) objects:  86% (932/1083), [192.00](http://192.0.0.0/) KiB | [362.Receiving](http://362.receiving/) objects:  87% (943/1083), [192.00](http://192.0.0.0/) KiB | [362.Receiving](http://362.receiving/) objects:  88% (954/1083), [192.00](http://192.0.0.0/) KiB | [362.Receiving](http://362.receiving/) objects:  89% (964/1083), [192.00](http://192.0.0.0/) KiB | [362.Receiving](http://362.receiving/) objects:  90% (975/1083), [192.00](http://192.0.0.0/) KiB | [362.Receiving](http://362.receiving/) objects:  91% (986/1083), [192.00](http://192.0.0.0/) KiB | [362.Receiving](http://362.receiving/) objects:  92% (997/1083), [192.00](http://192.0.0.0/) KiB | [362.Receiving](http://362.receiving/) objects:  93% (1008/1083), [192.00](http://192.0.0.0/) KiB | 362Receiving objects:  94% (1019/1083), [192.00](http://192.0.0.0/) KiB | 362Receiving objects:  95% (1029/1083), [192.00](http://192.0.0.0/) KiB | 362remote: Total 1083 (delta 38), reused 1077 (delta 37), pack-reused 0
Receiving objects:  96% (1040/1083), [192.00](http://192.0.0.0/) KiB | 362Receiving objects:  97% (1051/1083), [192.00](http://192.0.0.0/) KiB | 362Receiving objects:  98% (1062/1083), [192.00](http://192.0.0.0/) KiB | 362Receiving objects:  99% (1073/1083), [192.00](http://192.0.0.0/) KiB | 362Receiving objects: 100% (1083/1083), [192.00](http://192.0.0.0/) KiB | 362Receiving objects: 100% (1083/1083), [306.71](http://306.71/) KiB | [399.00](http://399.00/) KiB/s, done.
Resolving deltas: 100% (38/38), done.
fatal: detected dubious ownership in repository at '/storage/emulated/0/pif-generator/asus_i007_1'
To add an exception for this directory, call:

        git config --global --add [safe.directory](http://safe.directory/) /storage/emulated/0/pif-generator/asus_i007_1
./start: line 343: br_arr: bad array subscript
.

- Using format: json


! No [build.prop](http://build.prop/) files found in script directory

- Parsing [build.prop(s)](http://build.prop(s)/) ...


! No fingerprint found, unable to continue


- Parsing build UTC date ...
date: invalid date ‘@’
./start: line 126: [: : integer expression expected

- Parsing build first API level ...
No [vendor-build.prop](http://vendor-build.prop/) file found. Falling back to [build.prop](http://build.prop/) ...

- No first API level found, falling back to build SDK version ...

./start: line 153: [: : integer expression expected
./start: line 158: [: : integer expression expected

- Writing new custom [pif.json](http://pif.json/) ...
{
  "PRODUCT": "",
  "DEVICE": "",
  "MANUFACTURER": "",
  "BRAND": "",
  "MODEL": "",
  "FINGERPRINT": "",
  "FIRST_API_LEVEL": ""
}
Done!
```
</p>
</details> 

Short mode:

<details><summary>Click to expand</summary>
<p>

```logtalk
/sdcard/pif-generator $ bash ./start -s
----- Short mode -----
Paste repo URL here (or press Ctrl+C to stop): https://dumps.tadiphone.dev/dumps/blackview/bv9600.git
Cloning into 'bv9600'...
remote: Enumerating objects: 722, done.
remote: Counting objects: 100% (722/722), done.
remote: Compressing objects: 100% (515/515), done.
remote: Total 722 (delta 0), reused 721 (delta 0), pack-reused 0
Receiving objects:  68% (491/722), [140.00](http://140.0.0.0/) KiB | [263.0Receiving](http://263.0receiving/) objects:  69% (499/722), [140.00](http://140.0.0.0/) KiB | [263.0Receiving](http://263.0receiving/) objects:  70% (506/722), [140.00](http://140.0.0.0/) KiB | [263.0Receiving](http://263.0receiving/) objects:  71% (513/722), [140.00](http://140.0.0.0/) KiB | [263.0Receiving](http://263.0receiving/) objects:  72% (520/722), [140.00](http://140.0.0.0/) KiB | [263.0Receiving](http://263.0receiving/) objects:  73% (528/722), [140.00](http://140.0.0.0/) KiB | [263.0Receiving](http://263.0receiving/) objects:  74% (535/722), [140.00](http://140.0.0.0/) KiB | [263.0Receiving](http://263.0receiving/) objects:  75% (542/722), [140.00](http://140.0.0.0/) KiB | [263.0Receiving](http://263.0receiving/) objects:  76% (549/722), [140.00](http://140.0.0.0/) KiB | [263.0Receiving](http://263.0receiving/) objects:  77% (556/722), [140.00](http://140.0.0.0/) KiB | [263.0Receiving](http://263.0receiving/) objects:  78% (564/722), [140.00](http://140.0.0.0/) KiB | [263.0Receiving](http://263.0receiving/) objects:  79% (571/722), [140.00](http://140.0.0.0/) KiB | [263.0Receiving](http://263.0receiving/) objects:  80% (578/722), [140.00](http://140.0.0.0/) KiB | [263.0Receiving](http://263.0receiving/) objects:  81% (585/722), [140.00](http://140.0.0.0/) KiB | [263.0Receiving](http://263.0receiving/) objects:  82% (593/722), [140.00](http://140.0.0.0/) KiB | [263.0Receiving](http://263.0receiving/) objects:  83% (600/722), [140.00](http://140.0.0.0/) KiB | [263.0Receiving](http://263.0receiving/) objects:  84% (607/722), [140.00](http://140.0.0.0/) KiB | [263.0Receiving](http://263.0receiving/) objects:  85% (614/722), [140.00](http://140.0.0.0/) KiB | [263.0Receiving](http://263.0receiving/) objects:  86% (621/722), [140.00](http://140.0.0.0/) KiB | [263.0Receiving](http://263.0receiving/) objects:  87% (629/722), [140.00](http://140.0.0.0/) KiB | [263.0Receiving](http://263.0receiving/) objects:  88% (636/722), [140.00](http://140.0.0.0/) KiB | [263.0Receiving](http://263.0receiving/) objects:  89% (643/722), [140.00](http://140.0.0.0/) KiB | [263.0Receiving](http://263.0receiving/) objects:  90% (650/722), [140.00](http://140.0.0.0/) KiB | [263.0Receiving](http://263.0receiving/) objects:  91% (658/722), [140.00](http://140.0.0.0/) KiB | [263.0Receiving](http://263.0receiving/) objects:  92% (665/722), [140.00](http://140.0.0.0/) KiB | [263.0Receiving](http://263.0receiving/) objects:  93% (672/722), [140.00](http://140.0.0.0/) KiB | [263.0Receiving](http://263.0receiving/) objects:  94% (679/722), [140.00](http://140.0.0.0/) KiB | [263.0Receiving](http://263.0receiving/) objects:  95% (686/722), [140.00](http://140.0.0.0/) KiB | [263.0Receiving](http://263.0receiving/) objects:  96% (694/722), [140.00](http://140.0.0.0/) KiB | [263.0Receiving](http://263.0receiving/) objects:  97% (701/722), [140.00](http://140.0.0.0/) KiB | [263.0Receiving](http://263.0receiving/) objects:  98% (708/722), [140.00](http://140.0.0.0/) KiB | [263.0Receiving](http://263.0receiving/) objects:  99% (715/722), [140.00](http://140.0.0.0/) KiB | [263.0Receiving](http://263.0receiving/) objects: 100% (722/722), [140.00](http://140.0.0.0/) KiB | [263.0Receiving](http://263.0receiving/) objects: 100% (722/722), [193.78](http://193.0.0.78/) KiB | [289.00](http://289.00/) KiB/s, done.
fatal: detected dubious ownership in repository at '/storage/emulated/0/pif-generator/bv9600'
To add an exception for this directory, call:

        git config --global --add [safe.directory](http://safe.directory/) /storage/emulated/0/pif-generator/bv9600
./start: line 343: br_arr: bad array subscript
.

- Using format: json


! No [build.prop](http://build.prop/) files found in script directory
```

</p>
</details> 

Am I calling it wrong, or is there a bug? Thanks!

**Comment by juleast** [comment] 2024-01-28 16:33
This is probably happening because you cloned the tool in your `/sdcard` I don't think that path has proper permissions. Could you try cloning into another directory? Such as `/sdcard/tools`. Then delete all directories you cloned or better yet reclone this repo since there's not a lot to download. And report back if you have any problems. I'll also try investigating this issue and looking into whether or not I can reproduce the issue.

**Comment by juleast** [comment] 2024-02-02 06:07
Closing due to no reply.

**Closed as completed by juleast** 2024-02-02 06:07 UTC
